export { default as Login } from "./Login/Login";
// export { default as SellerLogin } from "./SellerLogin/Sellerlogin";
export { default as Signup } from "./Signup/Signup";
export { default as SellerSignup } from "./SellerSignup/SellerSignup";
export { default as Forgotpassword } from "./Forgotpassword/Forgotpassword";
export { default as Home } from "./Home/Home";
export { default as Contact } from "./Contact/Contact";
export { default as AboutUs } from "./About/About";
export { LiveRank } from "./live/LiveRank";
export { LiveSearch } from "./live/LiveSearch";
export { TiktokLiveProduct } from "./live/TiktokLiveProduct";
export { TopLiveCreators } from "./live/TopLiveCreators";
export { ProductSearch } from "./product/ProductSearch";
export { MostPromoted } from "./product/MostPromoted";
export { NewListed } from "./product/NewListed";
export { TopSelling } from "./product/TopSelling";
export { VideoProductRank } from "./product/VideoProductRank";
export { CreatorSearch } from "./Creator/CreatorSearch";
export { GrowthRank } from "./Creator/GrowthRank";
export { TrendingCreators } from "./Creator/TrendingCreators";
export { EcommerceRank } from "./Creator/EcommerceRank";
export { VerifiedCreatorRank } from "./Creator/VerifiedCreatorRank";
export { ShopMostPromoted } from "./Shop/MostPromoted";
export { ShopRank } from "./Shop/ShopRank";
export { ShopSearch } from "./Shop/ShopSearch";
